apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: <namespace>
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: <FLASK_RUN_PORT>
      targetPort: <FLASK_RUN_PORT>
