apiVersion: v1
kind: Service
metadata:
  name: {{app_name}}
  namespace: ctdeploytest
spec:
  selector:
    app: {{app_name}}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{service_port}}
      targetPort: {{app_port}}
